### ISSUE TITLE
if student id is set and query is complete and you resubmit without uploading a new picture the old picture is deleted

### ISSUE THREAD

**Issue by anjumun** [j-nicholson/laroche-student-evaluation-project#22]

**Comment by j-nicholson** [comment]
I looked a little into this issue and it seems like inputs of type file can not have their value attribute changed programmatically due to security reasons. For example, this could result in people getting files containing password information by uploading a path to that file and retrieving it back. It seems like the only way to go about this issue is to support drag and drop for files (which is the only way to programmatically change the value attribute of inputs of type file with Javascript as of recently). This does not seem to help our issue much, but there is a link to what it is talking about:

https://stackoverflow.com/questions/47515232/how-to-set-file-input-value-programatically-i-e-when-drag-dropping-files
